apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/dzoni223/my-app:latest  # Change this to your container registry
          ports:
            - containerPort: 8080
          env:
            - name: ENV_VAR
              value: "production"

